# Generated by Django 4.2.19 on 2025-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_author_library_librarian_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
